### ISSUE TITLE
Feature Image Upload error

### ISSUE THREAD

**Issue by YjangWynter** [sdescommunications/SDES-Communications-Theme-OSI#4]
Whenever adding staff or images as featured images, Word
![issue-fail](https://user-images.githubusercontent.com/21028927/70241351-e83cd980-173c-11ea-8355-96dfd3a6fe92.png)
![issue-next](https://user-images.githubusercontent.com/21028927/70241352-e83cd980-173c-11ea-8e41-19f9bfdbdc84.png)
![issue-start](https://user-images.githubusercontent.com/21028927/70241353-e83cd980-173c-11ea-9e11-d481b41b6148.png)

Press backend would not update.

**Comment by acardona-ucf** [comment]
this issue will be on this theme also but screenshots where taken from the OSI. So the OSI issue is corrected and will be added the fix to this theme as well.
